### ISSUE TITLE
yaml parser for instrument.geometry shapes and operations

### ISSUE THREAD

**Issue by yxqd** [danse-inelastic/instrument#6]
See also mcvine/workflow#17.

Example:
```
  rotation:
    block:
      width: 4.6*cm
      height: 4.6*cm
      thickness: 2.3/4*cm
    angle: 90*deg
    axis:
      beam: 0
      transversal: 1.
      vertial: 0
```
